# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
alert: !include alerts.yaml

sensor:
  - platform: time_date
    display_options:
      - "date"
      - "date_time"

recorder:
  auto_purge: true

panel_custom:
  - name: zwave-graph-panel
    url_path: zwave-graph
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:z-wave
    module_url: /local/zwavegraph3.js
    config:
      # ranker - pick one: network-simplex, tight-tree, longest-path
      ranker: network-simplex
      # edge_visibility - pick one: relevant, all
      edge_visibility: relevant
      # grouping - pick one: z-wave, ungrouped
      grouping: z-wave

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

input_boolean:
  prevent_deep_sleep:
    name: Prevent Deep Sleep
    icon: mdi:sleep-off
  fountain_ota_mode:
    name: Fountain in OTA Mode

notify:
  - platform: clicksend
    name: ClickSend
    username: !secret clicksend_user
    api_key: !secret clicksend_api_key
    recipient: !secret clicksend_phone
  - platform: group
    name: alexa_tts_group
    services:
      - service: alexa_media_kitchen_echo_show
        data:
          data:
            type: tts
      - service: notify
      - service: clicksend
  - platform: pushover
    name: Pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

logger:
