substitutions:
  device_name: water_sensor_1
  friendly_name: Laundry water sensor



esphome:
  name: "${device_name}"
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.1.199
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret wifi_fallback_pw
    
globals:
  - id: is_sensor_power
    type: bool
    initial_value: "false"

output:
  - platform: gpio
    pin: D1
    id: sensorPower
    
interval:
  - interval: 10s
    then:
      - lambda: |-
          if (id(is_sensor_power)){
            id(sensorPower).turn_off();
            id(is_sensor_power) = false;
          } else {
            id(sensorPower).turn_on();
            id(is_sensor_power) = true;
          }
  
binary_sensor:
  - platform: gpio
    pin: D0
    filters:
      - invert:
      - delayed_on: 11s
    name: "${friendly_name}"
    device_class: moisture
    id: "${device_name}_status"
    on_press:
      - while:
          condition:
            binary_sensor.is_on: "${device_name}_status"
          then:
          - switch.turn_on: led1
          - delay: 200ms
          - switch.turn_off: led1
          - delay: 100ms
          - switch.turn_on: led1
          - delay: 200ms
          - switch.turn_off: led1
          - delay: 400ms
    on_release:
      then:
        - switch.turn_off: led1

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi signal"
    id: "${device_name}_wifi_signal"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: "${device_name}_uptime"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "${friendly_name} ESPHome Version"
    id: "${device_name}_esphome_version"

switch:
  - platform: gpio
    pin:
      number: D4
      inverted: true
    id: led1

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
